/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { App as StylebookSite } from './components/stylebook-site/sttylebook-site';

interface HTMLStylebookSiteElement extends StylebookSite, HTMLElement {
}
declare var HTMLStylebookSiteElement: {
  prototype: HTMLStylebookSiteElement;
  new (): HTMLStylebookSiteElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "stylebook-site": HTMLStylebookSiteElement;
  }
  interface ElementTagNameMap {
      "stylebook-site": HTMLStylebookSiteElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "stylebook-site": JSXElements.StylebookSiteAttributes;
      }
  }
  namespace JSXElements {
      export interface StylebookSiteAttributes extends HTMLAttributes {
        
      }
  }
}

